### PR TITLE
Added Russian Language.

### PR DESCRIPTION
**Pull request by Ivanoshechka**
Doing this stuff on github second times in my life. (I am very confused. Xd)

So, I thought someone had already created a translation into my language, but one stuck on lambda, and no one did it here, so... I hope there will be my compatriots who will straighten me.

Btw, there a problem with text placement. (Line 105, 106.)
image
I can't shorten these words. _(Or i idiot, who don't know the own lang.)_
So yeah, fix it for another languages too?

### CODE REVIEW

**Comment by Ivanoshechka** [comment]
Btw, that's one on lambda, it's machine translator. Xd

**Comment by Ivanoshechka** [comment]
Btw, you can add on the Invert Right stuff (Line 105, 106.) additional window with an explanation. In order not to change the location of the switches. (Well, if you don't want to.)

**Comment by Ivanoshechka** [comment]
Okay, so this was a last update, it's final translate for adding.

**Comment by Motschen** [comment]
Thank you very much :)

**Pull request merged**
